version: "3.9"

services:
  web:
    image: furbor/basic-web-app
    container_name: basic-web-app
    environment: 
      #- PORT=3001
      - DATABASE_URL=postgresql://si5_sacc:dev_password@database:5432/td_1
    ports:
      #- 3001:3001
      - 3000:3000
    restart: unless-stopped
    networks:
      - basic-web-app_network
  
  database:
    image: postgres:13.4
    container_name: postgres-db
    environment:
      - POSTGRES_DB=td_1
      - POSTGRES_USER=si5_sacc
      - POSTGRES_PASSWORD=dev_password
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - basic-web-app_network

networks:
  basic-web-app_network:
    driver: bridge